### ISSUE TITLE
No prow jobs for this repository

### ISSUE THREAD

**Issue by houshengbo** [knative-sandbox/operator#2]
**Describe the bug**
When serving and eventing operators co-exist in one repository,
1. How to set up prow for projects under knative-sandbox?
2. How to set up the prow jobs? Do we consolidate them into one, or keep them separate for better issue track?

There are two type of jobs we need to consider:
```
pull-knative-serving-operator-integration-tests
pull-knative-eventing-operator-integration-tests
```

and
```
pull-knative-serving-operator-upgrade-tests
pull-knative-eventing-operator-upgrade-tests
```

When operators merge, keep them separate or consolidate into one?

**Expected behavior**
We can have prow jobs running for each PRs, verifying the quality of the code.

**To Reproduce**
Steps to reproduce the behavior.

**Knative release version**
The Knative version, where you find this issue.

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by evankanderson** [comment]
I think this was done here: https://github.com/knative/test-infra/pull/1851

**Comment by evankanderson** [comment]
Hmm, but Prow doesn't seem to be working here:

/close
