### ISSUE TITLE
Remove all duplicate transformer code

### ISSUE THREAD

**Issue by jcrossley3** [knative-sandbox/operator#26]
We don't want to maintain two separate code branches for the fields common to both `KnativeServing` and `KnativeEventing`. All of these files should be removed:

[pkg/reconciler/knativeeventing/common/config_maps.go](../tree/cf1f02a692de/pkg/reconciler/knativeeventing/common/config_maps.go)
[pkg/reconciler/knativeeventing/common/config_maps_test.go](../tree/cf1f02a692de/pkg/reconciler/knativeeventing/common/config_maps_test.go)
[pkg/reconciler/knativeserving/common/config_maps.go](../tree/cf1f02a692de/pkg/reconciler/knativeserving/common/config_maps.go)

[pkg/reconciler/knativeeventing/common/images.go](../tree/cf1f02a692de/pkg/reconciler/knativeeventing/common/images.go)
[pkg/reconciler/knativeeventing/common/images_test.go](../tree/cf1f02a692de/pkg/reconciler/knativeeventing/common/images_test.go)
[pkg/reconciler/knativeserving/common/images.go](../tree/cf1f02a692de/pkg/reconciler/knativeserving/common/images.go)
[pkg/reconciler/knativeserving/common/images_test.go](../tree/cf1f02a692de/pkg/reconciler/knativeserving/common/images_test.go)

Their consolidated versions should be relocated, but I'm not sure where. How about `pkg/transformers`?

**Comment by houshengbo** [comment]
Will they be used somewhere else other than in the code under pkg/reconciler?
Does pkg/reconciler/transformer work?

**Comment by jcrossley3** [comment]
> Does `pkg/reconciler/transformers` work?

Sure. Do you like that better than `pkg/reconciler/common`? (just in case we have shared stuff other than transformers)
